// MOVIES
export const FETCH_ALL_TODOS = 'FETCH_ALL_TODOS'
export const FETCH_DETAIL_TODOS = 'FETCH_DETAIL_TODOS'
export const POST_TODO = 'POST_TODO'
export const DONE_TODO = 'DONE_TODO'
export const UNDONE_TODO = 'UNDONE_TODO'
export const DELETE_TODO = 'DELETE_TODO'